<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="utf8">
    <title>Dziupla Marecka</title>
    <link href="style.css" rel="stylesheet">
    <link rel="icon" href="golomp.jpg" type="image/gif" sizes="16x16">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,600,1,0" />
    <?php
      session_start();
      if ($_SESSION['zalogowany'] === false) { 
        die('Odmowa dostępu!');
      }
      $folder = __DIR__;   
      if ($_SESSION['login'] !== basename($folder)) {
        die('Nie znalezio użytkownika!');
      }
    ?>
  </head>
  <body>
    
      <section id="sekcja_tytulowa">
        Witamy w Dziupli Mareckiej
        <div class="pod_tyt">
          <?php
          echo "jesteś zalogowany jako:   ", $_SESSION['login'];
          ?>
        </div>
      </section>
    <section id="sekcja_linkowa">
      <a href="patchnotes.html"><span class="material-symbols-outlined">note</span></a>
      <a href="strona_w_budowie-template.html"><span class="material-symbols-outlined">info</span></a>
      <a href="strona_w_budowie-template.html"><span class="material-symbols-outlined">movie</span></a>
      <a href="./../../REJESTRACJA I LOGOWANIE/PHP/PHP_wylogowanie.php"><span class="material-symbols-outlined">door_open</span></a>
    </section>
    <section id ="sekcja_kanalow">
     <?php require_once "./wyswietlanie_kanalow.php" ?> 
    </section>
    <br>
    <section id="sekcja_dodawania_kanalu">
      <br>
      <a href="./EDYCJA/edycja_kanalu.php">Edytuj kanały</a>
    </section>
    <br>
    <?php /*require_once "./zlicz.php" */?>
    <br>
    <br>
    <br>
    <br>
    <div id="cookies-message-container">  <!-- naprawic sciezke z ciaskammi bo tez sie popsulo-->
      <div id="cookies-message">
          Ta strona używa ciasteczek.... : - D
          <a onclick="WHCloseCookiesWindow();" id="accept-cookies-checkbox">OK OK</a>
      </div>
    </div>
    <script src="ciastka-okienko.js"></script>
    
    <footer>
    <hr>
    <br>
      Autrostwo: Mareckie koło miłośników  ludzików z kasztanów <br> --- <br>Generated by: Mlekovita Sp. Z.O.O
    </footer>
  </body>
</html>
